// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

import { Time } from "./Time";

/** State of a set of joints. Each joint is uniquely identified by its name. All non-empty arrays should have the same length. */
export type JointState = {
  /** Timestamp of the joint state data */
  timestamp: Time;

  /** Joint names */
  name: string[];

  /** Joint positions in radians (revolute) or meters (prismatic) */
  position: number[];

  /** Joint velocities in rad/s (revolute) or m/s (prismatic) */
  velocity: number[];

  /** Joint efforts in Nm (revolute) or N (prismatic) */
  effort: number[];
};
